language: go
sudo: false

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.13.x

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.23.8

script:
  # Run linter
  - golangci-lint run
  # Run tests
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: performix:yXTihlSzsLFSZiqbXMNzvTSX
