language: go
sudo: false

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.13.x

script:
  # Run tests
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: performix:yXTihlSzsLFSZiqbXMNzvTSX
