'name': 'lint urlfilter'
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
'on': 'push'
'jobs':
  'go-lint':
    'permissions':
      'contents': 'read'
    'runs-on': '${{ matrix.os }}'
    'strategy':
      'matrix':
        'os':
          - 'macos-latest'
          - 'ubuntu-latest'
    'steps':
      - 'uses': 'actions/checkout@master'
        'with':
          'fetch-depth': 0
          # Set to false to avoid  GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'uses': 'actions/setup-go@v3'
        'with':
          'go-version': '1.26.x'
      - 'name': 'run-lint'
        'run': 'make go-deps go-lint'
  'notify':
    'needs':
      - 'go-lint'
    # Secrets are not passed to workflows that are triggered by a pull request
    # from a fork.
    #
    # Use always() to signal to the runner that this job must run even if the
    # previous ones failed.
    'if': |
      ${{ always() &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    'runs-on': 'ubuntu-latest'
    'permissions':
      # Required by workflow-conclusion-action to check workflow status.
      'actions': 'read'
      'contents': 'read'
    'steps':
      - 'name': 'Conclusion'
        'uses': 'technote-space/workflow-conclusion-action@v1'
      - 'name': 'Send Slack notification'
        'uses': '8398a7/action-slack@v3'
        'with':
          'status': '${{ env.WORKFLOW_CONCLUSION }}'
          'fields': 'workflow, repo, message, commit, author, eventName, ref'
        'env':
          'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}'
          'SLACK_WEBHOOK_URL': '${{ secrets.SLACK_WEBHOOK_URL }}'
