'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.26.5--1' }}
  'CACHE_BUSTER': |-
    ${{ inputs.cache_buster || '0' }}
'jobs':
  'LintAndTestJobDocker':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Lint and test step'
        'run': |
          #!/bin/sh

          set -e -f -u -x

          docker build \
              --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
              --build-arg "CACHE_BUSTER=${CACHE_BUSTER}" \
              --output '.' \
              --progress 'plain' \
              --target 'tester-exporter' \
              -f ./docker/ci.Dockerfile \
              .

          exit_code="$(cat ./test-reports/test-exit-code.txt)"
          readonly exit_code

          exit "$exit_code"
'name': 'Lint and test workflow (private)'
'on':
  'push':
    'branches':
      - '*'
  'workflow_dispatch':
    'inputs':
      'cache_buster':
        'default': ''
        'description': |
          Override to force re-run of cached stages (pass any unique value).
        'type': 'string'
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
