'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.26.2--1' }}
  'CACHE_BUSTER': |-
    ${{ vars.CACHE_BUSTER || '0' }}
'jobs':
  'LintAndTestJob':
    'runs-on': |
      ${{ case(github.repository_owner == 'AdGuardSoftwareLimited', 'team-go', 'ubuntu-latest') }}
    'steps':
      - 'uses': 'actions/checkout@v6'
      - 'name': 'Lint and test step'
        'run': |
          #!/bin/sh

          set -e -f -u -x

          docker build \
              --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
              --build-arg "CACHE_BUSTER=${CACHE_BUSTER}" \
              --output '.' \
              --progress 'plain' \
              --target 'tester-exporter' \
              -f ./docker/ci.Dockerfile \
              .

              exit_code="$(cat ./test-reports/test-exit-code.txt)"
              readonly exit_code

              exit "$exit_code"
'name': 'Lint and test workflow'
'on':
  'push':
    'branches':
      - '*'
  'workflow_dispatch': null
